name: Pipeline with stages

on:
    push:
        branches:
            - main

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Build project
              run: echo "Building the project.."

    Test:
        runs-on: ubuntu-latest
        needs: Build
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Test project
              uses: echo "Running the Test..."
    Deploy:
        runs-on: ubuntu-latest
        needs: Test
        steps:
            - name: Cheeckout code
              uses: actions/checkout@v4
            - name: Deploy project
              uses: echo "Deploying the project..."
    